globalVariables(c("data", "CIlower", "CIupper", "EMint", "Effect", "MC", "PE", "Point", "ReliabilityRatio", "a", 
                  "astar", "call_yreg", "casecontrol", "env", "ereg", "estimation", "exposure",
                  "family_ereg", "family_mreg", "family_postcreg", "family_reg", 
                  "family_yreg", "full", "inference", "is_coxph_yreg", "is_glm_ereg", "is_glm_mreg",
                  "is_glm_postcreg", "is_glm_yreg", "is_lm_mreg", "is_lm_postcreg",
                  "is_lm_yreg", "is_lm_ereg", "is_multinom_ereg", "is_multinom_mreg", "is_multinom_postcreg",
                  "is_multinom_yreg", "is_polr_ereg", "is_polr_mreg",
                  "is_polr_postcreg", "is_polr_yreg", "is_survreg_yreg",
                  "is_svymultinom_mreg", "is_svyglm_yreg", "is_svyglm_mreg", "mediator", "model", "multimp", "mval", "n", "nboot", "outcome", "postc",
                  "postcreg", "basec", "basecval", "event", "weights_yreg", "y_case",
                  "y_control", "yprevalence", "yrare", "yref", "nRep", "a_lev", "y_lev", "args_mice",
                  "family_wmdenomreg", "family_wmnomreg", "is_glm_wmdenomreg", "is_glm_wmnomreg",
                  "is_lm_wmdenomreg", "is_lm_wmnomreg", "is_multinom_wmdenomreg",
                  "is_multinom_wmnomreg", "is_polr_wmdenomreg", "is_polr_wmnomreg",
                  "weights_wmmdenomreg", "wmdenomreg", "wmnomreg"))