# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        run: |
          sudo apt-get install pandoc

      - name: Install gfortran
        run: |
          brew install gcc
          ln -s $(brew --prefix)/bin/gfortran-$(brew list --versions gcc | awk '{print $2}') /usr/local/bin/gfortran

      - name: Install other system dependencies
        run: |
          brew install qpdf pkg-config checkbashisms

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Install package
        run: R CMD INSTALL .

      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual --as-cran
